name: desi_kitchen
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  mobile_scanner: ^3.5.2

  firebase_core: ^2.30.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.17.5

  qr_flutter: ^4.1.0
  url_launcher: ^6.1.14

  app_links: ^6.1.0   # 👈 ADD THIS LINE

  video_player: ^2.8.6

  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^17.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/punjabi/
    - assets/gujarati/
    - assets/desert/
    - assets/drink/
    - assets/home/
    - assets/images/
    - assets/video/   # ← add this for splash video

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icons/app_icon.png"