// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPQHPXRZlLhE5W9Ro27qKGKJsjlMyzzFs',
    appId: '1:104670809650:web:cfe527d2e67fb9d902b62b',
    messagingSenderId: '104670809650',
    projectId: 'desi-kitchen-56193',
    authDomain: 'desi-kitchen-56193.firebaseapp.com',
    storageBucket: 'desi-kitchen-56193.firebasestorage.app',
    measurementId: 'G-FP9SGT4YDZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDohp04ocHZjtokas9vbAqyB25gyUuORMQ',
    appId: '1:104670809650:android:aabdd11fcad0907e02b62b',
    messagingSenderId: '104670809650',
    projectId: 'desi-kitchen-56193',
    storageBucket: 'desi-kitchen-56193.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKDwTO9EkXKu5HvxHAeSfYu39ixIa5Ogs',
    appId: '1:104670809650:ios:a9a7349f657a971a02b62b',
    messagingSenderId: '104670809650',
    projectId: 'desi-kitchen-56193',
    storageBucket: 'desi-kitchen-56193.firebasestorage.app',
    iosBundleId: 'com.example.desiKitchen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKDwTO9EkXKu5HvxHAeSfYu39ixIa5Ogs',
    appId: '1:104670809650:ios:a9a7349f657a971a02b62b',
    messagingSenderId: '104670809650',
    projectId: 'desi-kitchen-56193',
    storageBucket: 'desi-kitchen-56193.firebasestorage.app',
    iosBundleId: 'com.example.desiKitchen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPQHPXRZlLhE5W9Ro27qKGKJsjlMyzzFs',
    appId: '1:104670809650:web:6317544d3e0d4c4e02b62b',
    messagingSenderId: '104670809650',
    projectId: 'desi-kitchen-56193',
    authDomain: 'desi-kitchen-56193.firebaseapp.com',
    storageBucket: 'desi-kitchen-56193.firebasestorage.app',
    measurementId: 'G-0RBZK0M7J6',
  );
}
